Add "comment-date" as output
peter-evans/find-comment pull request #88
Opened 2022-12-16 14:49 UTC by 0xCaso

Hope I didn't miss anything in the additions

2022-12-19 00:42 UTC, peter-evans requested changes
Hi @0xCaso 

Thank you for this contribution!

Just a couple of things to change before merging, but overall looks good! 👍

2022-12-19 00:42 UTC, peter-evans commented on README.md
> +The `comment-id`, `comment-body`, `comment-author` and `comment-date` of the matching comment found will be output for use in later steps.
Please also add a line to the example below.

```yml
echo ${{ steps.fc.outputs.comment-date }}
```

2022-12-19 00:42 UTC, peter-evans commented on src/main.ts
> +      core.setOutput('comment-date', comment.created_at)
I think we should call the output `comment-created-at`. It matches the GitHub API and is slightly clearer than "date" because it's a full timestamp including the time.

(jfyi: I didn't match the API for `comment-author` because in that case "user" or "login" is not very clear to users of this action. "author" makes more sense in context.)

2022-12-19 10:50 UTC, 0xCaso commented on src/main.ts
> +      core.setOutput('comment-date', comment.created_at)
Thanks for the suggestion. Sure, `comment-created-at` makes more sense

2022-12-19 10:50 UTC, 0xCaso commented
Thanks a lot for the suggestions!

2022-12-20 00:16 UTC, peter-evans approved these changes

2022-12-20 00:17 UTC, peter-evans commented
Thank you for the changes. Merging!

2022-12-20 00:17 UTC, merged

2022-12-20 01:22 UTC, peter-evans commented
Released as `v2.2.0` / `v2`